import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import { Avatar, Greeting } from "@/components/imports";
import Card from "@/components/Card/Card";
import { Links } from "@/data/links";
import AOS from 'aos'
import 'aos/dist/aos.css'; // You can also use <link> for styles
import { useEffect, useState } from "react";



export default function Home() {


 
  return (
    <>
      <Head>
        <title>Meus Links | Igor Vinicius</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
        <meta name="theme-color" content="#18082E" />
      </Head>
     
      <div className={styles.body}>
        <main className={styles.main}>
          <Avatar/>
          <Greeting/>
<div data-aos='fade-up' data-aos-delay='800'>
          {Links.map((link) => {
            return <Card url={link.url} title={link.title} subtitle={link.subtitle} icon={link.icon} key={link.title} />;
          })}
          </div>
        </main>
      </div>
    </>
  );
}
